#
# Creates a local development Docker environment
#

version: '2.1'

services:
  static-files:
    image: nginx:alpine
    volumes:
      - '../public:/usr/share/nginx/html/app/development:delegated'
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './nginx/ssl:/etc/nginx/ssl:ro'
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    healthcheck:
      disable: true
    depends_on:
      - app

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /srv/www/app
    volumes:
      - '../:/srv/www/app:delegated'
    environment:
      - NODE_ENV
      - PORT=8080
      - APP_DOMAIN
      - CDN_HOST_URL
      - OAUTH_CLIENT_ID
    ports:
      - '8080:8080'
      # Node debugger access:
      - '9231:9231'
    healthcheck:
      disable: true
