common: &common
  branches: '!HEAD'
  timeout_in_minutes: 60
  agents:
    queue: t2-large

wdio: &wdio
  branches: '!HEAD'
  artifact_paths: test/wdio/reports/*/**/*
  agents:
    queue: t2-large

steps:
  - name: security-check
    <<: *common
    branches: '*'
    command: bin/docker-node.sh yarn security-check
    agents:
      queue: default
    retry:
      automatic:
        exit_status: '*'
        limit: 10

  - name: build
    <<: *common
    command: >
      docker pull allthings/node &&
      bin/artifacts-build.sh
    artifact_paths: build/artifacts/*.tar.gz

  - wait

  - name: locales
    <<: *common
    command: >
      bin/artifacts-download.sh &&
      bin/docker-node.sh yarn locales:export
    agents:
      queue: default

  - name: lint
    <<: *common
    command: >
      bin/artifacts-download.sh &&
      bin/docker-node.sh yarn lint
    agents:
      queue: default

  - name: unit
    <<: *common
    command: >
      bin/artifacts-download.sh &&
      bin/docker-node.sh yarn test:unit

  - name: e2e-1
    <<: *common
    command: >
      bin/artifacts-download.sh &&
      rm -rf test/e2e/logs test/e2e/screenshots test/e2e/videos &&
      bin/screenshots-download.sh &&
      SCREENSHOTS_DIFF=true
      bin/e2e.sh --update --record
      --log mailhog,php,api,accounts,app,cockpit,nginx,chromedriver,graphql --group pipeline-1 &&
      bin/screenshots-upload.sh
    artifact_paths: >
      test/e2e/logs/**/*.log;test/e2e/screenshots/**/*.png;test/e2e/videos/**/*.mp4

  - name: e2e-2
    <<: *common
    command: >
      bin/artifacts-download.sh &&
      rm -rf test/e2e/logs test/e2e/screenshots test/e2e/videos &&
      bin/screenshots-download.sh &&
      SCREENSHOTS_DIFF=true
      bin/e2e.sh --update --record
      --log mailhog,php,api,accounts,app,cockpit,nginx,chromedriver,graphql --group pipeline-2 &&
      bin/screenshots-upload.sh
    artifact_paths: >
      test/e2e/logs/**/*.log;test/e2e/screenshots/**/*.png;test/e2e/videos/**/*.mp4

  - name: e2e-3
    <<: *common
    command: >
      bin/artifacts-download.sh &&
      rm -rf test/e2e/logs test/e2e/screenshots test/e2e/videos &&
      bin/screenshots-download.sh &&
      SCREENSHOTS_DIFF=true
      bin/e2e.sh --update --record
      --log mailhog,php,api,accounts,app,cockpit,nginx,chromedriver,graphql --group pipeline-3 &&
      bin/screenshots-upload.sh
    artifact_paths: >
      test/e2e/logs/**/*.log;test/e2e/screenshots/**/*.png;test/e2e/videos/**/*.mp4

  - name: e2e-4
    <<: *common
    command: >
      bin/artifacts-download.sh &&
      rm -rf test/e2e/logs test/e2e/screenshots test/e2e/videos &&
      bin/screenshots-download.sh &&
      SCREENSHOTS_DIFF=true
      bin/e2e.sh --update --record
      --log mailhog,php,api,accounts,app,cockpit,nginx,chromedriver,graphql --group pipeline-4 &&
      bin/screenshots-upload.sh
    artifact_paths: >
      test/e2e/logs/**/*.log;test/e2e/screenshots/**/*.png;test/e2e/videos/**/*.mp4

  - name: wdio / chrome / suite-1
    command: >
      bin/artifacts-download.sh &&
      test/wdio/bin/wdio.sh chrome --bail --suite suite-1
    <<: *wdio

  - name: wdio / chrome / suite-2
    command: >
      bin/artifacts-download.sh &&
      test/wdio/bin/wdio.sh chrome --bail --suite suite-2
    <<: *wdio

  #- name: wdio / chrome / suite-3
  #  command: >
  #    bin/artifacts-download.sh &&
  #    test/wdio/bin/wdio.sh chrome --bail --suite suite-3
  #  <<: *wdio

  - name: wdio / firefox / suite-1
    command: >
      bin/artifacts-download.sh &&
      test/wdio/bin/wdio.sh firefox --bail --suite suite-1
    <<: *wdio

  - name: wdio / firefox / suite-2
    command: >
      bin/artifacts-download.sh &&
      test/wdio/bin/wdio.sh firefox --bail --suite suite-2
    <<: *wdio

  #- name: wdio / firefox / suite-3
  #  command: >
  #    bin/artifacts-download.sh &&
  #    test/wdio/bin/wdio.sh firefox --bail --suite suite-3
  #  <<: *wdio

  - wait

  - name: build and push docker image
    <<: *common
    command: >
      bin/docker-push.sh allthings/app
    branches: master

  - name: notify e2e-sync
    command: bin/notify.sh e2e-sync
    branches: master

  - name: notify e2e
    command: bin/notify.sh e2e HEAD
    branches: master
